### PR TITLE
Fix main branch IT compilation errors after merging #7962

### PR DESCRIPTION
**Pull request by tdonohue**
## References
Related to #7962 and #3371

## Description
After merging #7962, several IT compilation errors (from ITs added in previously merged #3371) occurred on `main`.  This PR quickly fixes those errors. 

## Instructions for Reviewers
Verify ITs all now succeed.

### CODE REVIEW

**Comment by tdonohue** [comment]
Merging, as this fixes the IT failures on `main`.  There's one failing IT I had to disable with `@Ignore` as I just ran out of time today to debug it.  See https://github.com/DSpace/DSpace/pull/8009/commits/b6ec08746e5c674964a937cf28ff27cf8eb9cd91

**Comment by tdonohue** [comment]
@abollini and @Micheleboychuk :  This PR was merged today to fix ITs in #7962 that ended up conflicting with some recent changes on `main`.  Unfortunately, as part of this PR, I had to **disable an integration test** from #7962 in this commit: https://github.com/DSpace/DSpace/pull/8009/commits/b6ec08746e5c674964a937cf28ff27cf8eb9cd91

If either of you find time tomorrow, it's possible that disabled IT can be easily fixed.  I just ran out of time today to debug it, and wanted to get `main` minimally passing tests/building successfully again to unblock other PRs.
