### ISSUE TITLE
DSpace CSV export allows CSV injection to Excel with unfiltered content

### ISSUE THREAD

**Issue by ebalnaves** [DSpace/DSpace#9899]
## Describe the bug
If a user submits a document with a field value which could be interpreted as a function in Excel, the CSV export DSpaceCSVLine.java
 does not escape or sanitise this value.  The result is that a client opening this in Excel treating it as a trusted source (and with marcos enabled) will execute this function.

## To Reproduce
(1) Submit an item with a text value of =sum(1+1)

(2) Export the collection in using the DSpace metadata export.

(3) Open in Excel and note that the field resolves as "2"  - i.e. the formula is executed.

## Expected behavior

The cell value is prefixed by an apostrophe when it contains a potential excel function

The following is a proof of concept for sanitisation

        s = s.replaceAll("^[\\r\\n]+", "");
        if (s.length() > 1 && "+@=-".indexOf(s.charAt(0)) != -1) {
            s = s.substring(1);
        }

        // Replace internal quotes with two sets of quotes
        return "\"" + s.replaceAll("\"", "\"\"") + "\"";

## Related work
Link to any related tickets or PRs here.

**Comment by alanorth** [comment]
I think this sounds like Excel's problem, not ours?

**Comment by ebalnaves** [comment]
Yes it is.  However where DSpace sits in an trusted ecosystem with users of Excel the potential to inject such data is being treated as a problem with the providing system, even though the weakness is in Excel.   CVE's are being raised on just this point against the several library applications.    

Sanitising the data in CSV looks to be a relatively easy fix to DSpaceCSVLine.java in 6-8 versions.

**Comment by tdonohue** [comment]
I think the challenge with this is that *not everyone uses Excel* when editing a CSV.  While I'm not against sanitization (where possible), I think we need to ensure it doesn't impact the ability to edit those same CSVs in other tools.  We also need to ensure that the sanitization does *not* impact the newly imported CSV (i.e. would the metadata field in DSpace be updated to be sanitized or not?)

So, there may be side effects to this sanitization that we need to test for.

Regardless, this would need a volunteer to create a PR. Then we'd need to do some thorough testing to ensure the sanitization process doesn't break editing in other (non-Excel) tools, and doesn't break the re-import of that metadata.

**Comment by ebalnaves** [comment]
I created a PR on this for a snippet of code - we are using it already in some of our sites.  Feedback most appreciated.

**Comment by alanorth** [comment]
DSpace's workflows revolve around CSVs. The only thing we should be worried about is whether our CSVs are compliant with RFC 4180 (or whatever), as well as various DSpace-isms like id, collection, multiple value separators, and authorities. It is really _not our problem_ if Excel does something unsafe with the data in the file.

Personally, I use many CSV-based workflows: OpenRefine, `csv` from the Python stdlib, Pandas, etc. This could potentially break my workflows just to make sure that some Excel users don't get pwned.

Maybe a better solution is to have an "Excel export" mode that does this sanitation optionally.

**Comment by ebalnaves** [comment]
Unfortunately if a CVE is raised on the issue externally, there will be pressure to correct it in DSpace.   Institutions now actively monitor CVE's.    Other library systems are in exactly this situation.  As part of the enterprise ecosystem DSpace can't just say "it's their problem".     

The problem is of course that it may well be a dspace admin that is exporting and then opening the spreadsheet.  If a cunning person has submitted an item properly crafted this could be just the scenario the injection problem is anticipating.  Export, edit and import is a very common bulk metadata editing scenario.

I would be surprised if the solution (prepending an apostrophe only on certain leading characters) broke any downstream systems.  It is still a csv-encoded value.    You could undoubtedly argue that changing the metadata should never be done, but then again if you are told to take down the system, the metadata will not be much good to you.    

Interestingly the change could be reversed on the inbound route where the data is a change, because old and new values are there to be compared.   The prepended apostrophe could therefore be stripped.  Still working on that aspect.

We have some very large datasets, and  @ and = are not generally remarked.   Phone numbers with a + prefix are represented in the data.

We are already patching our instances to do the filtering (v6,7,8), and will monitor issues from there.  

Edmund

**Comment by alanorth** [comment]
If Excel is evaluating the literal text value `=1+1` as `2` that's Excel's problem, not ours.

> Unfortunately if a CVE is raised on the issue externally, there will be pressure to correct it in DSpace. Institutions now actively monitor CVE's. Other library systems are in exactly this situation. As part of the enterprise ecosystem DSpace can't just say "it's their problem".

A CVE will not be raised on DSpace due to a parsing issue in Excel. Furthermore, if you work in an organization that thinks this way you should push back on them. It's nonsense security theater. I regularly have to push back against such policies in my organization.

Excel does a lot of annoying stuff, for example converting all my YYYY dates to floats and mangling my ISBNs, not to mention endless issues with users opening UTF-8 encoded files in windows-1252 and corrupting anything outside of the ASCII range.

**Comment by ebalnaves** [comment]
The following CVE rated 8.8 was raised against the Koha open source system:

https://www.cvedetails.com/cve/CVE-2024-24337/

In many ways DSpace is worse that Koha here because an non-admin user can submit content which is then processed by an admin user.  At least requires an admin level login for the access.

The sad reality is an institution is not likely to say "get rid of MIcrosoft" but they might well say "get rid of DSpace" even if they spend an exorbitant amount for a replacement.

Indeed we have a client who is taking Koha off public access purely on the issue of Content Security Policy - something DSpace does not implement either.

Agencies, particularly government, are becoming very anxious  about attacks - the British Library being an example none want to emulate.

Edmund

**Comment by alanorth** [comment]
I disagree that the linked CVE is a vulnerability in Koha. Surprising that it got assigned a CVE in my opinion. Shame, because it creates a precedent for corporate ICT teams to point to. It is not DSpace's job to sanitize arbitrary text values just so Excel users don't receive prompts for code to run or have their formulas evaluated automatically.

When there are format parsing vulnerabilities in Android or whatever, of which there are many, we don't say that JPEGs are banned—we fix the parser. I could give other examples.

> Indeed we have a client who is taking Koha off public access purely on the issue of Content Security Policy - something DSpace does not implement either.

This is a fair point and was brought up recently (see: https://github.com/DSpace/DSpace/issues/9881).

**Comment by mwoodiupui** [comment]
If CVEs are filed against the wrong product, they should be corrected.

If we must paper over someone else's bad code, at least DSpace should offer the option to say "I know what I'm doing, so give me the bitstream without corrupting it."  But even that is setting a bad precedent.  DSpace should return the object that was archived, not some hacked variant.

**Comment by tdonohue** [comment]
Overall, I just want to note here that I **support** performing some sanitization of CSVs, provided it doesn't **change the data** on re-import.  I'm worried specifically that sanitization techniques could accidently modify **real data** in a unexpected way on re-import.

Like others here, I'm still not confident this rises to the level of a security issue (as we have no requirement that anyone should use Excel).  But, I understand the argument that DSpace should do it's best to ensure the safety/sanitization of _any exported content_.  

So, I agree that this is a bug that should be fixed, regardless of whether it is deemed a security issue or not.

**Comment by alanorth** [comment]
I have just created a CSV containing "injected" content from the user (myself) in LibreOffice Calc: [libreoffice-cve.csv](https://github.com/user-attachments/files/17438617/libreoffice-cve.csv). The file contains:

```csv
"id","comment"
1,"DDE (""cmd"";""/C cmd"";""!A0"")A0"
```

So by this logic LibreOffice is "vulnerable" too? And every other piece of software that allows you to arbitrarily create text files?

This is neither a bug nor a security vulnerability in DSpace. It's Excel's problem. In fact, according to [the CVE linked](https://nitipoom-jar.github.io/CVE-2024-24337/), Excel even prompts the user asking whether they want to run the content. The UX around communicating the risk to the user is Excel's problem, not ours.
